// Writes .github/reports/dependencies.md from `npm audit` + `npm outdated`.
//
// Deliberately contains no "generated at" timestamp: the file should change
// only when the dependency situation actually changes, so every commit to it
// carries real news and `git log` on the file is a genuine history of when
// advisories appeared and were cleared.
//
// Run with: npm run deps:report

import { execFileSync } from 'child_process';
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(root, '.github/reports/dependencies.md');

// Both commands exit non-zero when they have findings, which is not an error.
function npmJson(args) {
  try {
    return JSON.parse(execFileSync('npm', args, { cwd: root, encoding: 'utf-8' }) || '{}');
  } catch (err) {
    const stdout = err.stdout?.toString().trim();
    if (stdout) {
      try { return JSON.parse(stdout); } catch { /* fall through */ }
    }
    throw new Error(`npm ${args.join(' ')} produced no parsable JSON`);
  }
}

const SEVERITIES = ['critical', 'high', 'moderate', 'low', 'info'];

function vulnerabilitySection(audit) {
  const counts = audit.metadata?.vulnerabilities ?? {};
  const total = counts.total ?? 0;

  if (!total) return ['**No known vulnerabilities.**', ''];

  const summary = SEVERITIES
    .filter(s => counts[s])
    .map(s => `${counts[s]} ${s}`)
    .join(' · ');

  const rows = Object.values(audit.vulnerabilities ?? {})
    .sort((a, b) => SEVERITIES.indexOf(a.severity) - SEVERITIES.indexOf(b.severity))
    .map(v => {
      const titles = [...new Set(
        (v.via ?? []).filter(x => typeof x === 'object' && x.title).map(x => x.title)
      )];
      const detail = titles.length ? titles.join('; ') : `via ${(v.via ?? []).join(', ') || 'transitive dependency'}`;
      const fix = v.fixAvailable === true ? 'yes'
        : v.fixAvailable ? `\`${v.fixAvailable.name}@${v.fixAvailable.version}\`${v.fixAvailable.isSemVerMajor ? ' (breaking)' : ''}`
        : 'none';
      return `| \`${v.name}\` | ${v.severity} | ${detail} | ${fix} |`;
    });

  return [
    `**${total} vulnerability${total === 1 ? '' : 's'}** — ${summary}`,
    '',
    '| Package | Severity | Advisory | Fix |',
    '|---|---|---|---|',
    ...rows,
    '',
  ];
}

function outdatedSection(outdated, pkg) {
  const direct = new Set([
    ...Object.keys(pkg.dependencies ?? {}),
    ...Object.keys(pkg.devDependencies ?? {}),
  ]);

  const rows = Object.entries(outdated)
    .filter(([name]) => direct.has(name))
    .filter(([, info]) => info.current !== info.latest)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, info]) => {
      const major = (info.current ?? '').split('.')[0] !== (info.latest ?? '').split('.')[0];
      return `| \`${name}\` | ${info.current ?? '—'} | ${info.latest ?? '—'} | ${major ? 'major' : 'minor/patch'} |`;
    });

  if (!rows.length) return ['**All direct dependencies are on their latest version.**', ''];

  return [
    `**${rows.length} direct ${rows.length === 1 ? 'dependency is' : 'dependencies are'} behind latest.**`,
    '',
    '| Package | Current | Latest | Jump |',
    '|---|---|---|---|',
    ...rows,
    '',
  ];
}

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf-8'));
const audit = npmJson(['audit', '--json']);
const outdated = npmJson(['outdated', '--json']);

const md = [
  '# Dependency report',
  '',
  '_Generated by `npm run deps:report`. This file has no timestamp on purpose —',
  'it changes only when the dependency situation does, so its git history is a',
  'real record of when advisories appeared and were cleared._',
  '',
  '## Vulnerabilities',
  '',
  ...vulnerabilitySection(audit),
  '## Outdated direct dependencies',
  '',
  ...outdatedSection(outdated, pkg),
].join('\n') + '\n';

mkdirSync(dirname(OUT), { recursive: true });
const changed = !existsSync(OUT) || readFileSync(OUT, 'utf-8') !== md;
writeFileSync(OUT, md);

console.log(changed ? '✓ dependency report changed' : '· dependency report unchanged');
